---
- name: Download Jenkins LTS package
  become: yes
  get_url:
    url: "{{ jenkins_lts_package }}"
    dest: "{{ jenkins_package_download_path }}"

- name: Import jenkins rpm key
  become: yes
  rpm_key:
    state: present
    key: "{{ jenkins_rpm_key }}"

- name: Install Jenkins
  become: yes
  yum:
    name: jenkins
    state: installed

- name: Make sure Jenkins service is running
  systemd:
    state: started
    name: jenkins
    enabled: yes