---
jenkins_lts_package: 'http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo'
jenkins_package_download_path: '/etc/yum.repos.d/jenkins.repo'
jenkins_rpm_key: 'https://jenkins-ci.org/redhat/jenkins-ci.org.key'